version: "2.1"
services:
   plex:
      image: lscr.io/linuxserver/plex
      container_name: plex
      network_mode: host
      environment:
              - PUID=1000
              - PGID=1000
              - VERSION=docker
              - PLEX_CLAIM= #optional
      volumes:
              - ${DOWNLOADS_DIR}/Docker/Plex:/config
              - ${DOWNLOADS_DIR}:/media
      restart: unless-stopped

   deluge:
      restart: unless-stopped
      container_name: deluge
      image: binhex/arch-delugevpn
      ports:
              - "${IP}:8112:8112"
              - "${IP}:8118:8118"
              - "${IP}:58846:58846"
              - "${IP}:58946:58946"
      volumes:
              - ${DOWNLOADS_DIR}/Deluge/config:/config
              - ${DOWNLOADS_DIR}:/data
              - /etc/localtime:/etc/localtime:ro
      env_file: .env 
      environment:
              VPN_ENABLED: ${VPN_ENABLED}
              VPN_USER: ${VPN_USER}
              VPN_PASS: ${VPN_PASS}
              VPN_PROV: ${VPN_PROV}
              VPN_OPTIONS: ${VPN_OPTIONS}
              STRICT_PORT_FORWARD: ${STRICT_PORT_FORWARD}
              ENABLE_PRIVOXY: ${ENABLE_PRIVOXY}
              LAN_NETWORK: ${LAN_NETWORK}
              NAME_SERVERS: ${NAME_SERVERS}
              DELUGE_DAEMON_LOG_LEVEL: ${DELUGE_DAEMON_LOG_LEVEL}
              DELUGE_WEB_LOG_LEVEL: ${DELUGE_WEB_LOG_LEVEL}
              VPN_INPUT_PORTS: ${ADDITIONAL_PORTS}
              DEBUG: ${DEBUG}
              UMASK: ${UMASK}
              PUID: ${PUID}
              PGID: ${PGID}
      cap_add:
              - NET_ADMIN
   jellyfin:
      restart: unless-stopped
      image: linuxserver/jellyfin
      container_name: jellyfin
      ports:
              - 8096:8096
              - 8920:8920 
              - 7359:7359/udp 
              - 1900:1900/udp 
      volumes:
              - ${DOWNLOADS_DIR}/Jellyfin/config:/config
              - ${DOWNLOADS_DIR}/Jellyfin/cache:/cache
              - ${DOWNLOADS_DIR}:/media
      environment:
              PUID: 1100
              PGID: 1100
              TZ: America/New_York

