version: "3.8"
services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - UID=${UID}
      - GID=${GID}
      - NORDVPN_USERNAME=${NORDVPN_USERNAME}
      - NORDVPN_PASSWORD=${NORDVPN_PASSWORD}
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=p2p
    volumes:
      - ${CONFIG_DIR}/Nordvpn:/config
    restart: unless-stopped
    networks:
      - vpn

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    cap_add:
      - NET_ADMIN
    depends_on:
      - nordvpn
    ports:
      - "8112:8112"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Deluge:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped
    networks:
      - vpn

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ${CONFIG_DIR}/Jellyfin:/config
      - ${DOWNLOADS_DIR}:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Radarr:/config
      - ${DOWNLOADS_DIR}/Movies:/movies
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Sonarr:/config
      - ${DOWNLOADS_DIR}/Shows:/tv
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Lidarr:/config
      - ${DOWNLOADS_DIR}/Music:/music
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG_DIR}/Jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

networks:
  default:
    driver: bridge
  vpn:
    driver: bridge

